### ISSUE TITLE
How does fiery got its name?

### ISSUE THREAD

**Issue by patrick-llgc** [wayveai/fiery#1]
First of all, congrats on the great work! Really liked fiery introduced the temporal component to improve the baseline of lift-splat-shoot. 

Just curious, how does fiery got its name? FI is future instance I suppose, and I stopped from there :)

**Comment by anthonyhu** [comment]
Thanks for your kind words! Fiery stands for "Future Instance prEdiction in biRd's-Eye view".. :p
