### ISSUE TITLE
How can I get the visualization of road on the bev map? 

### ISSUE THREAD

**Issue by AlfredQin** [wayveai/fiery#12]
Hello, thanks for your great project !. Well , I find that there are road marking(drivable area) on the bev map except the vehicle semantic mask. So I am wondering how could you achieve that ?
Thank you !

**Comment by anthonyhu** [comment]
Thanks for your kind words! For visualisation, I load the NuScenes offline map of the scene and overlay on top of it the vehicle predictions. 

Does that answer your question?
