### ISSUE TITLE
loss < 0

### ISSUE THREAD

**Issue by YiJiangYue** [wayveai/fiery#15]
Hi, thanks for your great work. 
I have a question about loss. When i trained model for my data, the loss < 0 at epoch_0, is this normal?
Config: baseline.yaml in the project
![image](https://user-images.githubusercontent.com/35157509/141716911-45830c71-d032-4a66-bfd0-f2b3771efd3e.png)

**Comment by anthonyhu** [comment]
That's strange, all losses should be positive by definition. Do you know which loss is negative? (segmentation, kl?)

**Comment by YiJiangYue** [comment]
Seems to be caused by uncertainty. When i delete uncertainty weight, it seems to be normal. The uncertainty tends to be smaller than 0.

**Comment by YiJiangYue** [comment]
> That's strange, all losses should be positive by definition. Do you know which loss is negative? (segmentation, kl?)

Seems to be caused by uncertainty. When i delete uncertainty weight, it seems to be normal. The uncertainty tends to be smaller than 0.

**Comment by anthonyhu** [comment]
Oh yes that's correct, the uncertainty losses can be negative :)

**Comment by YiJiangYue** [comment]
> Oh yes that's correct, the uncertainty losses can be negative :)

so it's normal that loss_sum < 0 when i trained?

**Comment by anthonyhu** [comment]
Yup that's normal.

**Comment by YiJiangYue** [comment]
> normal

Thanks for your reply.
