### ISSUE TITLE
run visualise.py

### ISSUE THREAD

**Issue by sjbling** [wayveai/fiery#17]
How can I get the release data for running visualise.py

**Comment by anthonyhu** [comment]
Hi, the examples should be automatically downloaded when running `visualise.py` (they are stored in the urls listed here: https://github.com/wayveai/fiery/blob/master/visualise.py#L92)

**Comment by sjbling** [comment]
thanks, but https://github.com/wayveai/fiery/releases/download/v1.0 is a bad url.

**Comment by anthonyhu** [comment]
There are only 4 examples listed in the link:

```
'https://github.com/wayveai/fiery/releases/download/v1.0/example_1.npz',
'https://github.com/wayveai/fiery/releases/download/v1.0/example_2.npz',
'https://github.com/wayveai/fiery/releases/download/v1.0/example_3.npz',
'https://github.com/wayveai/fiery/releases/download/v1.0/example_4.npz'
```

and these urls work
