### ISSUE TITLE
data loading

### ISSUE THREAD

**Issue by sjbling** [wayveai/fiery#19]
why the lenth of self.indices   is 10? Is this means only train 10 samples data?

**Comment by anthonyhu** [comment]
That's when debugging using the "mini" NuScenes dataset. If you train the model on the full dataset as specified in the config https://github.com/wayveai/fiery/blob/master/fiery/configs/baseline.yml the dataset size is much bigger.

**Comment by sjbling** [comment]
thanks for your repply, I find that the index in the list always smaller than 10+sequence length, can you tell me why?
