### ISSUE TITLE
question about instance_flow

### ISSUE THREAD

**Issue by qfwysw** [wayveai/fiery#21]
Thanks for your excellent work!
I have some questions about instance_flow.
`warped_instance_seg = {}
    # t0,f01-->t1; t1,f12-->t2; t2,f23-->t3
    # t1,f10-->t0; t2,f21-->t1
    for t in range(1, seq_len):
        warped_inst_t = warp_features(instance_img[t].unsqueeze(0).unsqueeze(1).float(), # 1, 1, 200, 200
                                      future_egomotion_inv[t - 1].unsqueeze(0), mode='nearest',
                                      spatial_extent=spatial_extent)
        warped_instance_seg[t] = warped_inst_t[0, 0]
`
In your paper,  "Finally, we obtain feature flow labels by comparing the position of the instance centers of gravity between two consecutive timesteps".I think the code should convert t to t-1, not t-1 to t. How can it get the feature flow? I'm really confuesd about it. I'm looking forward your replying.

**Comment by anthonyhu** [comment]
Hi! Thanks for your kind words :)

The lines of code you're referring to compute the instance segmentation labels in the reference frame of the present. 
The flow features are computed here: https://github.com/wayveai/fiery/blob/master/fiery/utils/instance.py#L70
