### ISSUE TITLE
bug report, incorrect center label

### ISSUE THREAD

**Issue by XinchaoGou** [wayveai/fiery#3]
Hi guys,
I'd like to report a bug. 
https://github.com/wayveai/fiery/blob/d8aad07bf20c9a284645d7a8208a4bc292a9e8dd/fiery/utils/instance.py#L33
This line here should be 
![image](https://user-images.githubusercontent.com/35408641/124237347-030a4680-db4a-11eb-8762-068d3ab4e791.png)

Otherwise, the center label may miss the last one.
before change
![476E480F-2109-4FA9-B69C-074FB83B1962](https://user-images.githubusercontent.com/35408641/124238465-37323700-db4b-11eb-8695-2b1f12a85b8e.png)

after change
![A1A3AA8E-2847-4205-88B4-DCEA79E38FEB](https://user-images.githubusercontent.com/35408641/124238480-3bf6eb00-db4b-11eb-867b-fa01fcac8646.png)

**Comment by anthonyhu** [comment]
Hey Xinchao! Nice find, thanks for reporting the bug, it's now fixed in 746129c5fdb3ae7dd48daa5a9a46c4ab5fc6d6a9 :)
