### ISSUE TITLE
AssertionError: Database version not found: /opt1/data/nuscenes/trainval/v1.0-trainval

### ISSUE THREAD

**Issue by you-old** [wayveai/fiery#35]
AssertionError: Database version not found: /opt1/data/nuscenes/trainval/v1.0-trainval

**Comment by hemanth-v25** [comment]
@you-old  @anthonyhu , I'm facing the same issue. Did you solve this? If you did, please provide the fix.

**Comment by gsg213** [comment]
Depending on how you have your nuscenes folder organized you may need to change the line 435 in data.py for 
`dataroot = cfg.DATASET.DATAROOT`

That should works.
