### ISSUE TITLE
Is future_egopose necessary for inference?

### ISSUE THREAD

**Issue by synsin0** [wayveai/fiery#36]
Thanks for your great work. I have a little question about future ego pose during inference? I may find a little tricky because flow prediction is a module before motion planning. In real cases, the flow prediction module has no chance of getting future ego pose. But the code may show future ego pose is irreplacable in inference. When I turn to None, the inference doesn't work.

**Comment by synsin0** [comment]
I have understood the receptive field in the model, then info from future has been masked. No problems.

**Comment by viv365** [comment]
Hy synsin0, can u explain in detail about this future_ego_motion ? i am also having lot of confusion about this !

**Comment by anthonyhu** [comment]
`future_egomotion` is used to warp the past features to the present's reference frame, see https://github.com/wayveai/fiery/blob/master/fiery/models/fiery.py#L143
