### ISSUE TITLE
May I know where is the checkpoint getting saved? 

### ISSUE THREAD

**Issue by pranavi77** [wayveai/fiery#39]
I dont see anywhere that the checkpoint is getting saved and while resuming the training, I am getting an error that "size mismatch for model.temporal_model.model.1.aggregation.0.conv.weight"

**Comment by anthonyhu** [comment]
Hi,

The weights are saved in `fiery/tensorboard_logs` by default. You can change this folder by modifying the `LOG_DIR` field in https://github.com/wayveai/fiery/blob/master/fiery/config.py

Have you changed the size of the temporal model while resuming traning?

**Comment by pranavi77** [comment]
I am able to see only events.out file and yaml file in logs. I don't see any ckpt or meta file getting saved.

**Comment by pranavi77** [comment]
got it thank  you so much. somehow my default folder is not being created.
