### ISSUE TITLE
Generating labels

### ISSUE THREAD

**Issue by songqi-github** [wayveai/fiery#5]
Hi, I saw that you are also one of the contributors of tom-roddick/mono-semantic-maps. And I got some trouble in generating BEV semantic labels of nuScenes.
The label I generated is like:
![7446aa94bb76462794c4bac0d11c793b](https://user-images.githubusercontent.com/64065947/129177402-8655c4f6-55cf-4410-a9f9-6b5d9005e7d4.png)
![d60278e424329d3d3d8c986bd91468f](https://user-images.githubusercontent.com/64065947/129178247-ea080a8c-a86c-4d3f-b3a4-39d8805ef25b.png)

Is it right? And how to visualize it in color? Waiting for your answer and thanks a lot!

**Comment by anthonyhu** [comment]
Hi, 

Please raise an issue directly in the corresponding github repository.

Best,
Anthony
