### ISSUE TITLE
Visualization about distribution of futures

### ISSUE THREAD

**Issue by Crayon-new** [wayveai/fiery#52]
Hi, thanks for your great work!
I am very interested in the future distribution visualization in figure 1, could you please tell me how to plot it?
<img width="632" alt="image" src="https://github.com/wayveai/fiery/assets/56301098/a64d14fe-f2c5-4af7-bd93-78ebc960be9c">

**Comment by anthonyhu** [comment]
Hello, to get this figure, I've generated different future trajectories by sampling a 100 times. Starting from a bird's-eye view image full of zeros, I then increment each cell whenever a trajectory passes through the cell. This image is then obtained by visualising the heatmap of the bird's-eye view cell counts. 

If a trajectory is very likely, the cell count will be very high. Conversely, if a trajectory is very rare, it will have a low cell count.
