### ISSUE TITLE
All losses become NaN after about 1 epoch of training

### ISSUE THREAD

**Issue by jwookyoo** [wayveai/fiery#8]
Hi, 

Thank you for sharing this great work!

When I ran the training code, I got NaN for all losses after about 1 epoch of training. 
This problem is reproduced whenever I run the training code. (I have tested it three times.)

I followed the same environment setting with anaconda, and also used the same hyper-parameters. 
(The only difference is that our PyTorch version is 1.7.1 and yours is 1.7.0, and all other modules are the same as yours.)

Please share your idea about this problem, if you have any. Thanks!

**Comment by jwookyoo** [comment]
I loaded the weights first following your suggestion, and the training works now (without NaN)! Thanks a lot!!

**Comment by jwookyoo** [comment]
Can I ask one more question? :-) How can I train the FIERY Static weights from scratch?

**Comment by anthonyhu** [comment]
Of course. To train the FIERY Static from scratch, point the training script to the following config: https://github.com/wayveai/fiery/blob/master/fiery/configs/literature/static_lss_setting.yml

**Comment by jwookyoo** [comment]
I see. Thanks a lot!

**Comment by anthonyhu** [comment]
You're welcome!
